
const APP = window.APP_DATA;
const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];
let currentSlide = 1;
function fmt(v,d=3){ if(!Number.isFinite(v)) return 'not available'; if(Math.abs(v)>=10000 || (Math.abs(v)<.001 && v!==0)) return v.toExponential(2); return v.toFixed(d).replace(/0+$/,'').replace(/\.$/,''); }
function esc(t){ return String(t).replace(/[&<>"']/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c])); }
function nums(t){ return String(t).split(/[\s,;]+/).map(Number).filter(Number.isFinite); }
function mean(a){return a.reduce((s,v)=>s+v,0)/a.length;} function sd(a){ if(a.length<2)return NaN; const m=mean(a); return Math.sqrt(a.reduce((s,v)=>s+(v-m)**2,0)/(a.length-1)); }
function setStatus(t){ $('#statusMeter').textContent=t; $('#srStatus').textContent=t; }
function slideSrc(n){ return `assets/slides/slide-${String(n).padStart(2,'0')}.png`; }
function tr(n){ return APP.slides.find(s=>s.number===n) || {number:n,title:`Slide ${n}`,text:'Transcript unavailable.'}; }
function openTab(id){ $$('.tab').forEach(t=>{const on=t.dataset.tab===id;t.classList.toggle('active',on);t.setAttribute('aria-selected',String(on));t.tabIndex=on?0:-1;}); $$('.tab-panel').forEach(p=>{const on=p.id===id;p.classList.toggle('active',on);p.hidden=!on;}); setStatus(id); }
function setupTabs(){ $$('.tab').forEach(tab=>{ tab.addEventListener('click',()=>openTab(tab.dataset.tab)); tab.addEventListener('keydown',e=>{const tabs=$$('.tab'); const i=tabs.indexOf(tab); let j=i; if(e.key==='ArrowDown'||e.key==='ArrowRight')j=(i+1)%tabs.length; if(e.key==='ArrowUp'||e.key==='ArrowLeft')j=(i-1+tabs.length)%tabs.length; if(e.key==='Home')j=0; if(e.key==='End')j=tabs.length-1; if(j!==i){e.preventDefault();tabs[j].focus();openTab(tabs[j].dataset.tab);}});}); $('#toggleTextMode').addEventListener('click',()=>{const on=document.body.classList.toggle('text-first'); $('#toggleTextMode').setAttribute('aria-pressed',String(on));}); $('#toggleTranscripts').addEventListener('click',()=>{const on=document.body.classList.toggle('hide-transcripts'); $('#toggleTranscripts').textContent=on?'Show transcripts':'Hide transcripts'; $('#toggleTranscripts').setAttribute('aria-pressed',String(!on));}); $('#openAccessibilityGuide').addEventListener('click',()=>$('#accessibilityGuide').hidden=false); $('#closeAccessibilityGuide').addEventListener('click',()=>$('#accessibilityGuide').hidden=true); }
function renderChunks(){ APP.chunks.forEach(ch=>{const box=$(`#strip-${ch.id}`); if(!box)return; const slides=[]; for(let n=ch.start;n<=Math.min(ch.end,ch.start+5);n++) slides.push(n); box.innerHTML=slides.map(n=>`<button class="slide-thumb" type="button" data-slide="${n}"><img src="${slideSrc(n)}" alt="Thumbnail of slide ${n}"><span>Slide ${n}: ${esc(tr(n).title)}</span></button>`).join('');}); $$('.slide-thumb').forEach(b=>b.addEventListener('click',()=>{updateSlide(Number(b.dataset.slide));openTab('slides');})); }
function renderLectureMap(){ $('#lectureMap').innerHTML=APP.chunks.map(ch=>`<button class="lecture-card" type="button" data-slide="${ch.start}"><strong>Slides ${esc(ch.range)}: ${esc(ch.label)}</strong><p>${esc(ch.goals.join(' • '))}</p></button>`).join(''); $$('#lectureMap .lecture-card').forEach(b=>b.addEventListener('click',()=>updateSlide(Number(b.dataset.slide)))); }
function updateSlide(n){ currentSlide=Math.max(1,Math.min(APP.slideCount,Number(n)||1)); const info=tr(currentSlide); $('#slideNumber').value=currentSlide; $('#mainSlideImage').src=slideSrc(currentSlide); $('#mainSlideImage').alt=`Lecture slide ${currentSlide}: ${info.title}`; $('#saveSlide').href=slideSrc(currentSlide); $('#saveSlide').setAttribute('download',`${APP.repo}-slide-${String(currentSlide).padStart(2,'0')}.png`); $('#mainSlideTranscript').innerHTML=`<h3>Slide ${currentSlide}: ${esc(info.title)}</h3><p>${esc(info.text)}</p>`; setStatus(`slide ${currentSlide}`); }
function setupSlideStudio(){ $('#prevSlide').addEventListener('click',()=>updateSlide(currentSlide-1)); $('#nextSlide').addEventListener('click',()=>updateSlide(currentSlide+1)); $('#slideNumber').addEventListener('input',e=>updateSlide(e.target.value)); $('#printSlide').addEventListener('click',()=>{document.body.classList.add('print-slide'); window.print(); setTimeout(()=>document.body.classList.remove('print-slide'),500);}); updateSlide(1); }
function renderPractice(){ const cards=APP.practice||[]; const topics=['All topics',...new Set(cards.map(c=>c.topic))]; $('#practiceTopic').innerHTML=topics.map(t=>`<option value="${esc(t)}">${esc(t)}</option>`).join(''); $('#practiceTopic').addEventListener('change',renderPracticeCards); $('#practiceSearch').addEventListener('input',renderPracticeCards); $('#collapseKeys').addEventListener('click',()=>{$$('.key-text,.hint-text').forEach(x=>x.hidden=true); $$('.reveal-key').forEach(b=>{b.textContent='Reveal key'; b.setAttribute('aria-expanded','false');}); $$('.hint-key').forEach(b=>b.textContent='Hint');}); $('#printPractice').addEventListener('click',()=>{document.body.classList.add('print-practice'); window.print(); setTimeout(()=>document.body.classList.remove('print-practice'),500);}); renderPracticeCards(); }
function renderPracticeCards(){ const topic=$('#practiceTopic').value||'All topics'; const term=$('#practiceSearch').value.trim().toLowerCase(); const filtered=(APP.practice||[]).filter(c=>(topic==='All topics'||c.topic===topic) && (!term || `${c.prompt} ${c.key} ${c.topic}`.toLowerCase().includes(term))); $('#practiceCards').innerHTML=filtered.map(c=>`<article class="practice-card"><header><div><h3>Question ${c.number}</h3><span class="badge">${esc(c.topic)} · ${esc(c.difficulty)}</span></div><div class="button-row"><button class="ghost hint-key" type="button" data-id="${c.number}">Hint</button><button class="ghost reveal-key" type="button" data-id="${c.number}" aria-controls="key-${c.number}" aria-expanded="false">Reveal key</button></div></header><p class="question-text">${esc(c.prompt)}</p><div class="hint-text" id="hint-${c.number}" hidden>${esc(c.hint||'Start by identifying the lecture concept and known quantities.')}</div><div class="key-text" id="key-${c.number}" hidden>${esc(c.key)}</div></article>`).join('') || '<p>No practice cards were extracted for this section yet.</p>'; $$('.hint-key').forEach(b=>b.addEventListener('click',()=>{const x=$(`#hint-${b.dataset.id}`);x.hidden=!x.hidden;b.textContent=x.hidden?'Hint':'Hide hint';})); $$('.reveal-key').forEach(b=>b.addEventListener('click',()=>{const x=$(`#key-${b.dataset.id}`);x.hidden=!x.hidden;b.textContent=x.hidden?'Reveal key':'Hide key';b.setAttribute('aria-expanded',String(!x.hidden));})); setStatus(`${filtered.length} cards`); }
function table(headers,rows){return `<table class="mini-table"><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${esc(c)}</td>`).join('')}</tr>`).join('')}</tbody></table>`;}
function drawAxes(ctx,w,h){ctx.clearRect(0,0,w,h);ctx.fillStyle='#fff';ctx.fillRect(0,0,w,h);ctx.strokeStyle='#d6e0e4';ctx.strokeRect(50,25,w-80,h-70);}
function runTool(){ const k=APP.kind; const out=$('#toolOutput'); const tbl=$('#toolTable'); const canvas=$('#toolCanvas'); const ctx=canvas?canvas.getContext('2d'):null; if(k==='intro'){const ex=+$('#gradeExam').value, wk=+$('#gradeWork').value, ew=+$('#gradeExamWeight').value/100; const total=ex*ew+wk*(1-ew); const checked=$$('.checkItem').filter(c=>c.checked).length; out.className='result-box success'; out.innerHTML=`<p>Projected course average: <strong>${fmt(total,1)}%</strong>.</p><p>Weekly success checklist complete: ${checked}/4 items.</p>`; tbl.innerHTML=table(['Component','Contribution'],[['Exam average',fmt(ex*ew,1)],['Work average',fmt(wk*(1-ew),1)],['Total',fmt(total,1)]]);}
 else if(k==='units'){const factors={ug:1e-6,mg:1e-3,g:1,kg:1000,mL:1e-3,L:1}; const v=+$('#uValue').value, from=$('#uFrom').value,to=$('#uTo').value; const conv=v*factors[from]/factors[to]; const M=(+$('#mol').value)/(+$('#vol').value); const ppm=(+$('#mol').value*100000)/(+$('#mass').value/1000); out.className='result-box success'; out.innerHTML=`<p>${v} ${from} = <strong>${fmt(conv,5)} ${to}</strong>.</p><p>Molarity = ${fmt(M,5)} M. Approximate ppm from entered mass basis = ${fmt(ppm,3)} ppm.</p>`; tbl.innerHTML=table(['Quantity','Value'],[['Converted value',`${fmt(conv,5)} ${to}`],['Molarity',`${fmt(M,5)} M`],['Approx ppm',`${fmt(ppm,3)} ppm`]]);}
 else if(k==='precision'){const truev=+$('#trueVal').value,b=+$('#bias').value,sc=+$('#scatter').value; const vals=Array.from({length:8},(_,i)=>truev+b+(Math.sin(i*2.17)*sc)); const m=mean(vals), s=sd(vals), err=m-truev; out.className='result-box success'; out.innerHTML=`<p>Mean = <strong>${fmt(m,4)}</strong>; s = ${fmt(s,4)}; bias from true value = ${fmt(err,4)}.</p><p>${Math.abs(err)>s?'Accuracy concern: bias is larger than the replicate scatter.':'Precision dominates: scatter is comparable to or larger than bias.'}</p>`; tbl.innerHTML=table(['Replicate','Value'],vals.map((v,i)=>[i+1,fmt(v,4)])); if(ctx){const w=canvas.width,h=canvas.height;drawAxes(ctx,w,h);ctx.strokeStyle='#b74352';ctx.beginPath();ctx.moveTo(60,h/2);ctx.lineTo(w-40,h/2);ctx.stroke();vals.forEach((v,i)=>{ctx.fillStyle='#087f8c';ctx.beginPath();ctx.arc(80+i*(w-140)/(vals.length-1),h/2-(v-truev)*80,8,0,Math.PI*2);ctx.fill();});}}
 else if(k==='qa'){const x=nums($('#calX').value), y=nums($('#calY').value); const n=Math.min(x.length,y.length); const xs=x.slice(0,n), ys=y.slice(0,n); const mx=mean(xs), my=mean(ys); const m=xs.reduce((s,xi,i)=>s+(xi-mx)*(ys[i]-my),0)/xs.reduce((s,xi)=>s+(xi-mx)**2,0); const bb=my-m*mx; const unk=(+$('#unknownSignal').value-bb)/m; const ssTot=ys.reduce((s,yi)=>s+(yi-my)**2,0); const ssRes=ys.reduce((s,yi,i)=>s+(yi-(m*xs[i]+bb))**2,0); const r2=1-ssRes/ssTot; out.className='result-box success'; out.innerHTML=`<p>Calibration: y = ${fmt(m,5)}x + ${fmt(bb,5)}, R² = ${fmt(r2,5)}.</p><p>Unknown concentration from signal = <strong>${fmt(unk,5)}</strong>.</p>`; tbl.innerHTML=table(['Standard x','Signal y','Fit y'],xs.map((xi,i)=>[fmt(xi),fmt(ys[i]),fmt(m*xi+bb)])); if(ctx){const w=canvas.width,h=canvas.height;drawAxes(ctx,w,h); const maxx=Math.max(...xs,unk), maxy=Math.max(...ys,+$('#unknownSignal').value); xs.forEach((xi,i)=>{ctx.fillStyle='#087f8c';ctx.fillRect(55+xi/maxx*(w-100)-4,h-50-ys[i]/maxy*(h-90)-4,8,8);}); ctx.strokeStyle='#c98d17';ctx.beginPath();ctx.moveTo(55,h-50-bb/maxy*(h-90));ctx.lineTo(w-45,h-50-(m*maxx+bb)/maxy*(h-90));ctx.stroke();}}
 else if(k==='specintro'){const c=2.99792458e8,hc=6.62607015e-34; const unit=$('#lambdaUnit').value; const mult=unit==='nm'?1e-9:unit==='um'?1e-6:1; const lam=+$('#lambda').value*mult; const nu=c/lam, e=hc*nu; const nm=lam/1e-9; const region=nm<10?'X-ray/short UV':nm<400?'UV':nm<700?'visible':nm<2500?'near IR':'IR or longer'; out.className='result-box success'; out.innerHTML=`<p>Frequency = <strong>${fmt(nu,3)} Hz</strong>; photon energy = ${fmt(e,3)} J.</p><p>This wavelength is in the ${region} region.</p>`; tbl.innerHTML=table(['Property','Value'],[['Wavelength',`${fmt(nm,2)} nm`],['Frequency',`${fmt(nu,3)} Hz`],['Energy',`${fmt(e,3)} J`],['Region',region]]); if(ctx){drawAxes(ctx,canvas.width,canvas.height);ctx.fillStyle='#087f8c';ctx.fillRect(Math.min(canvas.width-80,60+Math.log10(Math.max(1,nm))*85),80,12,120);}}
 else if(k==='atomic'){const T=+$('#temp').value, amu=+$('#massAtom').value, lam=+$('#atomLambda').value; const rel=Math.sqrt(T/amu)*1e-6; out.className='result-box success'; out.innerHTML=`<p>Estimated relative Doppler broadening index: <strong>${fmt(rel,5)}</strong>.</p><p>Higher temperature and lower atomic mass broaden lines, which can reduce selectivity.</p>`; tbl.innerHTML=table(['Variable','Effect'],[['Temperature',`${T} K: higher means broader lines`],['Atomic mass',`${amu} amu: lower means broader lines`],['Wavelength',`${lam} nm line being observed`]]); if(ctx){drawAxes(ctx,canvas.width,canvas.height);['sample','atomizer','monochromator','detector'].forEach((s,i)=>{ctx.fillStyle='#eef6f7';ctx.fillRect(60+i*155,120,120,55);ctx.strokeRect(60+i*155,120,120,55);ctx.fillStyle='#172026';ctx.fillText(s,75+i*155,153);});}}
 else if(k==='uvvis'){const eps=+$('#epsilon').value,b=+$('#path').value,c=+$('#conc').value; const A=eps*b*c; const T=Math.pow(10,-A); out.className='result-box success'; out.innerHTML=`<p>A = εbc = <strong>${fmt(A,4)}</strong>; transmittance = ${fmt(T*100,3)}%.</p><p>${A>1.5?'Warning: high absorbance often needs dilution for reliable calibration.':'Absorbance is in a practical calibration range.'}</p>`; tbl.innerHTML=table(['Quantity','Value'],[['epsilon',eps],['path length',`${b} cm`],['concentration',`${c} M`],['absorbance',fmt(A,4)],['%T',fmt(T*100,3)]]); if(ctx){drawAxes(ctx,canvas.width,canvas.height);ctx.strokeStyle='#087f8c';ctx.beginPath();for(let x=0;x<520;x++){const wl=250+x;const y=120*Math.exp(-1*((wl-430)/70)**2)+60*Math.exp(-1*((wl-620)/90)**2);const px=60+x*(canvas.width-110)/520, py=canvas.height-45-y;if(x===0)ctx.moveTo(px,py);else ctx.lineTo(px,py);}ctx.stroke();}}
 else if(k==='fluorescence'){const ex=+$('#ex').value, em=+$('#em').value, q=+$('#quencher').value; const shift=em-ex; const relI=1/(1+q*10); out.className=shift>0?'result-box success':'result-box warning'; out.innerHTML=`<p>Stokes shift = <strong>${fmt(shift,1)} nm</strong>. Relative intensity with quencher = ${fmt(relI,3)}.</p><p>${shift>0?'Emission is at longer wavelength than excitation, as expected for fluorescence.':'Check wavelengths: emission is usually longer than excitation.'}</p>`; tbl.innerHTML=table(['Property','Value'],[['Excitation',`${ex} nm`],['Emission',`${em} nm`],['Stokes shift',`${fmt(shift,1)} nm`],['Relative intensity',fmt(relI,3)]]); if(ctx){drawAxes(ctx,canvas.width,canvas.height);[[ex,'#315f9a'],[em,'#b74352']].forEach(([wl,col])=>{ctx.strokeStyle=col;ctx.beginPath();for(let x=0;x<520;x++){const v=250+x;const y=140*Math.exp(-1*((v-wl)/35)**2);const px=60+x*(canvas.width-110)/520, py=canvas.height-45-y;if(x===0)ctx.moveTo(px,py);else ctx.lineTo(px,py);}ctx.stroke();});}}
 else {const e0=+$('#e0').value,n=+$('#ne').value,ox=+$('#ox').value,red=+$('#red').value,T=273.15+(+$('#tempC').value); const R=8.314462618,F=96485.33212; const Q=red/ox; const E=e0-(R*T/(n*F))*Math.log(Q); out.className='result-box success'; out.innerHTML=`<p>E = <strong>${fmt(E,4)} V</strong> using Q = reduced/oxidized = ${fmt(Q,4)}.</p><p>Changing activity changes the measured potential through the Nernst logarithm.</p>`; tbl.innerHTML=table(['Quantity','Value'],[['E0',`${e0} V`],['n',n],['Q',fmt(Q,4)],['Temperature',`${fmt(T,2)} K`],['E',`${fmt(E,4)} V`]]); if(ctx){drawAxes(ctx,canvas.width,canvas.height);ctx.strokeStyle='#087f8c';ctx.beginPath();for(let i=0;i<100;i++){const q=Math.pow(10,-3+i*6/99);const y=e0-(8.314*T/(n*96485))*Math.log(q);const px=55+i*(canvas.width-100)/99, py=canvas.height-50-(y-(e0-.18))/.36*(canvas.height-90);if(i===0)ctx.moveTo(px,py);else ctx.lineTo(px,py);}ctx.stroke();}}
}
function init(){setupTabs();renderChunks();renderLectureMap();setupSlideStudio();renderPractice(); const btn=$('#runMainTool'); if(btn)btn.addEventListener('click',runTool); runTool(); openTab('chunk1');}
document.addEventListener('DOMContentLoaded',init);
